variables:
  ADDITIONAL_CA_CERT_BUNDLE: |
    -----BEGIN CERTIFICATE-----
    MIIDTzCCAjegAwIBAgIQXUIJCZlo/L9DS+HyRXaM9zANBgkqhkiG9w0BAQsFADA6
    MRIwEAYKCZImiZPyLGQBGRYCUlUxEzARBgoJkiaJk/IsZAEZFgNVU0IxDzANBgNV
    BAMTBlVTQi1DQTAeFw0yMTEwMjkxMjU4NDdaFw0yNjEwMjkxMzA4NDZaMDoxEjAQ
    BgoJkiaJk/IsZAEZFgJSVTETMBEGCgmSJomT8ixkARkWA1VTQjEPMA0GA1UEAxMG
    VVNCLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvtylx7hlf9KL
    0JaURtOr1l8s9IC16yiv0Ak6vACJfhL8RthkVIhL1QXGcTgJ2d39oPEXHHb5g9fT
    H2FB2ang9+6JuUP40pArzLWQxifprZ/6ty5f35x8Ve0YPgDOPGIuAlU440v6F1BA
    ImZRzY/I2B6yau1pF4MRIoi9wqW6mJglycnw71hXYzJnyU8QroamrTCi7CoqT+pD
    IIXWQX4YtRoHHKEMsfaN8SY5L9JryCtlm5xXWbDx7FPsP80J43Ov93qxFcSBIpwE
    +o09+QCOrZAGI4vfQJAUzUj+Uq9zQEK/pi9fUiejJguCQTE5sw4NWmE9pj7iMZQ/
    9uw32350mQIDAQABo1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAd
    BgNVHQ4EFgQUPzEZJXrAKJeIqnxqryz3POCPCEYwEAYJKwYBBAGCNxUBBAMCAQAw
    DQYJKoZIhvcNAQELBQADggEBAJI19mzZu6ovqrwLlYiyzbK5Pkv6qSeHbRUY/j8f
    NnzUldZG2QMMoPSih2MT5iNN1svxEXVYTlcLm38r1ZI7R54Uc9wA8qX/MkGZB+76
    dSyX9Rrz9eJSr3CcL1Tbm6AH1u33PdU+WtyEsTDxSWJ+MLk7v1gd0lsiXFg/s7Wr
    rdj/ogD8RHnrFtTyugiC4DXO9UmpdY78lfCGSS/iZz/uXu7IydCSQfV0L765qdR0
    6LwI49yALti54xK0QNjTBtcpq5i2n9CdrMnoXjuSqSpONoMrCYtJZGA8MvTMxgrd
    GQImPcyZJGUuEEJtYKEWAabYtJ5fDBGTJQ4i9SJPe7A794E=
    -----END CERTIFICATE-----
stages:
  - test
test_job:
  tags:
    - windows
  stage: test
  image: node:lts
  before_script:
    - node -v
    - corepack enable
    - yarn config set -H enableImmutableInstalls false
    - yarn set version berry
    - yarn config set -H compressionLevel mixed
    - yarn config set -H nodeLinker node-modules
    - yarn config set -H enableStrictSsl false
    - yarn config set -H enableGlobalCache false
    - yarn config set -H 'npmRegistries["//git.usb.ru/api/v4/packages/npm/"].npmAlwaysAuth' true
    - yarn config set -H 'npmRegistries["//git.usb.ru/api/v4/packages/npm/"].npmAuthToken' "${CI_JOB_TOKEN}"
    - yarn config set -H npmScopes.contact.npmRegistryServer "https://${CI_SERVER_HOST}/api/v4/packages/npm/"
    - yarn config set -H npmScopes.motivation.npmRegistryServer "https://${CI_SERVER_HOST}/api/v4/packages/npm/"
    - yarn config set -H npmScopes.tools.npmRegistryServer "https://${CI_SERVER_HOST}/api/v4/packages/npm/"
    - yarn config set -H npmScopes.sql-tools.npmRegistryServer "https://${CI_SERVER_HOST}/api/v4/packages/npm/"
  script:
    - yarn
    - yarn build
    - export SSHPASS=$HOST_PASSWORD
    - sshpass -e scp -o stricthostkeychecking=no -r dist/* $HOST_USER@$HOST_NAME:$PATH_UPLOAD
  artifacts:
    paths:
      - dist/latest.yml
      - dist/*.exe
      - dist/*.exe.blockmap
    expire_in: 1 day
  cache:
    paths:
      - .yarn
      - node_modules
